#pragma once

#define TAPPING_TERM 170
#define PERMISSIVE_HOLD
#define LAYER_LOCK_IDLE_TIMEOUT 60000  // Turn off after 60 seconds.
#define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 5000  // 5 seconds.

#define MOUSEKEY_INTERVAL 5
#define MOUSEKEY_MOVE_DELETA 2
#define MOUSEKEY_MAX_SPEED 20
#define MK_KINETIC_SPEED
